name: Pages
on:
  push:
    paths:
      - vangen.json
  schedule:
    # At 06:00 UTC on Monday.
    - cron: '0 6 * * 1'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2
      - name: Set up Pages
        uses: actions/configure-pages@v1.0.0
      - name: Set up Go
        uses: ./.github/actions/setup-go-with-cache
      - name: Install vangen
        run: go install 4d63.com/vangen@v1.2.0
      - name: Install golds
        run: go install go101.org/golds@v0.4.9
      - name: Build pages
        run: |-
          vangen -out _site
          golds -dir=_site/doc -gen -silent -footer=simple -wdpkgs-listing=solo all
          touch _site/.nojekyll
          cat >_site/404.html <<'EOF'
          <!doctype html>
          <!--
            The following meta go-import is for Go modules in private monorepo.
            Note that this file is a valid XML; see https://go.dev/issue/39748
            In addition to that, it should be safe to respond with 404, see
            https://groups.google.com/d/topic/golang-nuts/1kewLH-Vack
          -->
          <meta name="go-import" content="go.pact.im/private git https://gitlab.com/pact/pact-go">
          <title>Page not found</title>
          <pre>404 page not found</pre>
          EOF
          echo go.pact.im >_site/CNAME
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1.0.1
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1.0.6
