name: Pages
on:
  push:
    paths:
      - vangen.json
  schedule:
    # At 06:00 UTC on Monday.
    - cron: '0 6 * * 1'
  workflow_dispatch:

# See https://github.com/actions/deploy-pages/pull/35
permissions:
   contents: read
   pages: write
   id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
       name: github-pages
       url: ${{ steps.deploy-pages.outputs.page_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2
      - name: Set up Go
        uses: actions/setup-go@v3.2.0
        with:
          go-version-file: .go-version
          cache: true
          cache-dependency-path: '**/go.sum'
      - name: Install vangen
        run: go install 4d63.com/vangen@v1.2.0
      - name: Install golds
        run: go install go101.org/golds@v0.4.9
      - name: Build pages
        run: |
          vangen -out=_site
          golds -dir=_site/doc -gen -silent -footer=simple -wdpkgs-listing=solo all
          touch _site/.nojekyll
          echo go.pact.im >_site/CNAME
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v0.1.0
      - name: Deploy pages
        id: deploy-pages
        uses: actions/deploy-pages@v1.0.4
        with:
          emit_telemetry: false
